import React, { createContext, useContext, useEffect, useState } from 'react';

type Language1 = 'th' | 'en';

type LanguageContextType = {
  language1: Language1;
  setLanguage1: (lang: Language1) => void;
  t: (key: string, params?: Record<string, any>) => string;
};

// Translation dictionary
const translations: Record<Language1, Record<string, string>> = {
  th: {
    // Job Details
    'jobDetail.apply': 'สมัครงาน',
    'jobDetail.requirements': 'คุณสมบัติ',
    'jobDetail.benefits': 'สวัสดิการ',
    'jobDetail.description': 'รายละเอียดงาน',
    'jobDetail.location': 'สถานที่ทำงาน',
    'jobDetail.type': 'ประเภทงาน',
    'jobDetail.experience': 'ประสบการณ์',
    'jobDetail.education': 'การศึกษา',
    'jobDetail.expandedImage': 'ภาพขยาย',
    'jobDetail.selectedImage': 'ภาพที่เลือก',
    'jobDetail.thumbnail': 'ภาพขนาดย่อ',
    'jobDetail.recommendedVideos': 'วีดีโอแนะนำ',
    'jobDetail.licenseDocuments': 'เอกสารหนังสือใบอนุญาต',
    'jobDetail.certificateImage': 'ภาพใบรับรอง',
    'jobDetail.defaultJobTitle': 'เกษตรกร ปลูกข้าวสาลี',
    'jobDetail.positionsAvailable': 'เปิดรับ {count} ตำแหน่ง',
    'jobDetail.interested': 'สนใจงาน',
    'jobDetail.alreadyInterested': 'สนใจงานแล้ว',
    'jobDetail.jobDetails': 'รายละเอียดงาน',
    'jobDetail.jobType': 'ประเภทงาน',
    'jobDetail.workDays': 'วันทำงาน',
    'jobDetail.workHours': 'เวลาทำงาน',
    'jobDetail.qualifications': 'คุณสมบัติผู้สมัคร',
    'jobDetail.workLocation': 'สถานที่ทำงาน',
    'jobDetail.errors.cannotDelete': 'ไม่สามารถลบได้: ข้อมูลถูกใช้งานแล้ว',
    'jobDetail.errors.unknownError': 'เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุ กรุณาลองอีกครั้ง',
    'jobDetail.errors.errorOccurred': 'เกิดข้อผิดพลาด',
    'jobDetail.errors.interestError': 'เกิดข้อผิดพลาดในการสนใจงาน กรุณาลองอีกครั้ง',
    'jobDetail.preview': 'ดูตัวอย่าง',
    'jobDetail.noVideosAvailable': 'ไม่มีวีดีโอที่นำเสนอในขณะนี้',
    'jobDetail.salaryStart': 'เงินเดือนเริ่มต้น',
    'jobDetail.workingHoursPerWeek': 'เวลาทำงาน: {count} ชั่วโมง/เดือน',
    'jobDetail.candidateCriteria': 'เกณฑ์การคัดเลือกผู้สมัคร',
    'mapSection.workplaceMap': 'แผนที่สถานที่ทำงาน',
    'mapSection.workplaceLocation': 'สถานที่ทำงาน',

    // Job Creation Form
    'create.pageTitle': 'สร้างประกาศงานใหม่',
    'create.backToList': 'กลับไปหน้ารายการ',
    'create.basicInfo': 'ข้อมูลพื้นฐาน',
    'create.salaryAndTime': 'เงินเดือนและเวลาทำงาน',
    'create.jobDetails': 'รายละเอียดงาน',
    'create.workLocation': 'สถานที่ทำงาน',
    'create.mediaSection': 'รูปภาพและวิดีโอ',

    'create.jobTitle': 'ชื่อตำแหน่งงาน',
    'create.jobType': 'ประเภทงาน',
    'create.selectJobType': 'เลือกประเภทงาน',
    'create.company': 'ผู้ว่าจ้าง',
    'create.selectCompany': 'เลือกผู้ว่าจ้าง',
    'create.jobManpower': 'ผู้จัดหา',
    'create.selectJobManpower': 'เลือกผู้จัดหา',
    'create.titleMedia': 'รูปภาพ/วิดีโอหน้าปก',
    'create.uploadImageOrVideo': 'อัพโหลดรูปภาพหรือวิดีโอ',
    'create.dragAndDrop': 'หรือลากและวางที่นี่',
    'create.positions': 'จำนวนที่เปิดรับ',
    'create.numericOnly': 'ระบุเป็นตัวเลขจำนวนเต็มเท่านั้น',
    'create.score': 'คะแนน',
    'create.slide': 'Slide',
    'create.notSlide': 'Not Slide',
    'create.salaryStart': 'เงินเดือนเริ่มต้น (บาท)',
    'create.workingHoursPerWeek': 'เวลาทำงานชั่วโมงต่อเดือน',
    'create.salaryEnd': 'เงินเดือนสูงสุด (บาท)',
    'create.startDay': 'วันเริ่มงาน',
    'create.endDay': 'วันสิ้นสุด',
    'create.startTime': 'เวลาเริ่มงาน',
    'create.endTime': 'เวลาเลิกงาน',
    'create.description': 'รายละเอียดงาน',
    'create.descPlaceholder': 'อธิบายรายละเอียดของงาน หน้าที่ความรับผิดชอบ',
    'create.qualifications': 'คุณสมบัติ',
    'create.qualiPlaceholder': 'ระบุคุณสมบัติที่ต้องการ เช่น อายุ เพศ การศึกษา',
    'create.criteria': 'เกณฑ์การคัดเลือก',
    'create.criteriaPlaceholder': 'ระบุเกณฑ์การคัดเลือกผู้สมัคร',
    'create.address': 'ที่อยู่',
    'create.addressPlaceholder': 'ระบุที่อยู่สถานที่ทำงาน',
    'create.location': 'พิกัด (Latitude, Longitude)',
    'create.locationPlaceholder': '13.7563,100.5018',
    'create.locationHelp': 'กรุณาระบุพิกัดในรูปแบบ Latitude,Longitude เช่น 13.7563,100.5018',
    'create.images': 'รูปภาพ',
    'create.uploadImages': 'อัพโหลดรูปภาพ',
    'create.imageTypes': 'PNG, JPG, GIF สูงสุด 10MB ต่อไฟล์',
    'create.videos': 'วิดีโอ',
    'create.uploadVideos': 'อัพโหลดวิดีโอ',
    'create.videoTypes': 'MP4, WebM สูงสุด 100MB ต่อไฟล์',

    // Days of week
    'create.monday': 'จันทร์',
    'create.tuesday': 'อังคาร',
    'create.wednesday': 'พุธ',
    'create.thursday': 'พฤหัสบดี',
    'create.friday': 'ศุกร์',
    'create.saturday': 'เสาร์',
    'create.sunday': 'อาทิตย์',

    // Buttons
    'create.cancel': 'ยกเลิก',
    'create.save': 'บันทึก',
    'create.saving': 'กำลังบันทึก...',

    // Validation & errors
    'create.required': 'จำเป็น',
    'create.validationLocation': 'กรุณาระบุพิกัดในรูปแบบ Latitude,Longitude เช่น 13.7563,100.5018',
    'create.fileFormatError': 'กรุณาเลือกไฟล์รูปภาพหรือวิดีโอเท่านั้น',
    'create.loading': 'กำลังโหลดข้อมูล...',
    'create.noCompany': 'ไม่พบข้อมูลผู้ว่าจ้าง',
    'create.noJobType': 'ไม่พบข้อมูลประเภทงาน',
    'create.noManpower': 'ไม่พบข้อมูลผู้จัดหา',

    // Modal texts
    'create.emptyManpowerTitle': 'ไม่พบข้อมูลผู้จัดหา',
    'create.emptyManpowerDesc': 'คุณจำเป็นต้องสร้างผู้จัดหาอย่างน้อย 1 รายการก่อนสร้างประกาศงานใหม่',
    'create.createManpower': 'สร้างผู้จัดหา',
    'create.emptyCompanyTitle': 'ไม่พบข้อมูลผู้ว่าจ้าง',
    'create.emptyCompanyDesc': 'คุณจำเป็นต้องสร้างข้อมูลบริษัทอย่างน้อย 1 รายการก่อนสร้างประกาศงานใหม่',
    'create.createCompany': 'สร้างผู้ว่าจ้าง',
    'create.emptyJobTypeTitle': 'ไม่พบข้อมูลประเภทงาน',
    'create.emptyJobTypeDesc': 'คุณจำเป็นต้องสร้างข้อมูลประเภทงานอย่างน้อย 1 รายการก่อนสร้างประกาศงานใหม่',
    'create.createJobType': 'สร้างประเภทงาน',

    // Additional translations for create page
    'create.jobOwner': 'เจ้าของงาน',
    'create.jobOwnerPlaceholder': 'ระบุชื่อเจ้าของงาน',
    'create.fileNotSelected': 'ยังไม่ได้เลือกไฟล์',
    'create.preview': 'รูปภาพหรือวิดีโอจะแสดงที่นี่',
    'create.removeMedia': 'ลบสื่อ',
    'create.removeImage': 'ลบรูปภาพ',
    'create.removeVideo': 'ลบวิดีโอ',
    'create.workingDays': 'วันทำงาน',
    'create.workingHours': 'เวลาทำงาน',
    'create.to': 'ถึง',
    'create.jobDescription': 'รายละเอียดงาน',
    'create.jobDescriptionPlaceholder': 'อธิบายรายละเอียดของงาน หน้าที่ความรับผิดชอบ',
    'create.successTitle': 'สร้างประกาศงานสำเร็จ',
    'create.successDescription': 'ประกาศงานถูกสร้างเรียบร้อยแล้ว',
    'create.viewJob': 'ดูประกาศงาน',
    'create.errorTitle': 'เกิดข้อผิดพลาด',
    'create.errorDescription': 'ไม่สามารถสร้างประกาศงานได้ กรุณาลองใหม่อีกครั้ง',
    'create.goBack': 'กลับไป',
    'create.selectMedia': 'เลือกรูปภาพหรือวิดีโอ',
    'create.uploadLimit': 'อัปโหลดได้สูงสุด {count} ไฟล์',
    'create.salaryRange': 'ช่วงเงินเดือน',
    'create.acceptingPositions': 'จำนวนตำแหน่งที่เปิดรับ',
    'create.scoreType': 'ประเภทคะแนน',
    'create.scoreValue': 'ค่าคะแนน',
    'create.dragDropHint': 'ลากและวางไฟล์ที่นี่ หรือคลิกเพื่อเลือกไฟล์',
    'create.workingPeriod': 'ช่วงเวลาทำงาน',
    'create.dayFrom': 'ตั้งแต่วัน',
    'create.dayTo': 'ถึงวัน',
    'create.timeFrom': 'ตั้งแต่เวลา',
    'create.timeTo': 'ถึงเวลา',
    'create.additionalDetails': 'รายละเอียดเพิ่มเติม',
    'create.locationDetails': 'รายละเอียดสถานที่',
    'create.mediaUpload': 'อัปโหลดสื่อ',
    'create.languageSelector': 'เลือกภาษา',
    'create.thai': 'ไทย',
    'create.english': 'อังกฤษ',
    'create.validationRequired': 'โปรดกรอกข้อมูลในช่องนี้',
    'create.validationNumber': 'กรุณากรอกเป็นตัวเลขเท่านั้น',
    'create.validationPositiveNumber': 'กรุณากรอกตัวเลขมากกว่า 0',
    'create.validationMaxLength': 'กรอกได้สูงสุด {count} ตัวอักษร',
    'create.validationImage': 'รองรับเฉพาะไฟล์รูปภาพ (JPG, PNG, GIF)',
    'create.validationVideo': 'รองรับเฉพาะไฟล์วิดีโอ (MP4, WebM)',
    'create.validationFileSize': 'ขนาดไฟล์ต้องไม่เกิน {size}MB',
    'create.confirmCancel': 'คุณแน่ใจหรือไม่ว่าต้องการยกเลิก?',
    'create.confirmCancelDescription': 'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'create.confirmCancelYes': 'ใช่, ยกเลิก',
    'create.confirmCancelNo': 'ไม่, ทำต่อ',
    'create.chooseLocation': 'เลือกตำแหน่งบนแผนที่',
    'create.browse': 'เลือกไฟล์',
    'create.jobOwnerLabel': 'เจ้าของงาน',
    'create.noFileSelected': 'ยังไม่ได้เลือกไฟล์',
    'create.imageOrVideoWillBeDisplayedHere': 'รูปภาพหรือวิดีโอจะแสดงที่นี่',
    'create.enterWholeNumberOnly': 'ระบุเป็นตัวเลขจำนวนเต็มเท่านั้น',
    'create.imagesAndVideos': 'รูปภาพและวิดีโอ',
    'create.candidateCriteria': 'เกณฑ์การคัดเลือกผู้สมัคร',
    'create.startDate': 'วันเริ่มงาน',
    'create.endDate': 'วันสิ้นสุด',
    'create.imageOrVideo': 'รูปภาพหรือวิดีโอ',
    'create.fileSizeError': 'ขนาดไฟล์ต้องไม่เกิน 500KB',
    'create.close': 'ปิด',
    'create.emptyJobTypesTitle': 'ไม่พบข้อมูลประเภทงาน',
    'create.emptyJobTypesDesc': 'คุณจำเป็นต้องสร้างข้อมูลประเภทงานอย่างน้อย 1 รายการก่อนสร้างประกาศงานใหม่',
    'create.emptyJobTypesCreate': 'สร้างประเภทงาน',
    'create.errorInvalidFile': 'กรุณาเลือกไฟล์รูปภาพหรือวิดีโอเท่านั้น',
    'create.acceptFormat': 'รับรูปภาพและวิดีโอ',

    'edit.backToJobs': 'กลับไปหน้าประกาศงาน',
    'edit.editJob': 'แก้ไขประกาศงาน',
    'edit.loading': 'กำลังโหลด',
    'edit.error': 'เกิดข้อผิดพลาด',
    'edit.success': 'แก้ไขประกาศงานสำเร็จ',
    'edit.goBack': 'กลับไป',
    'edit.jobDetails': 'รายละเอียดงาน',
    'edit.jobTitle': 'ชื่อประกาศงาน',
    'edit.jobOwner': 'เจ้าของงาน',
    'edit.score': 'คะแนน',
    'edit.salaryStart': 'เงินเดือนเริ่มต้น',
    'edit.salaryEnd': 'เงินเดือนสิ้นสุด',
    'edit.startDate': 'วันเริ่มงาน',
    'edit.endDate': 'วันสิ้นสุด',
    'edit.jobDate': 'วันที่',
    'edit.timeStart': 'เวลาเริ่มต้น',
    'edit.timeEnd': 'เวลาสิ้นสุด',
    'edit.description': 'รายละเอียดงาน',
    'edit.qualifications': 'คุณสมบัติ',
    'edit.address': 'ที่อยู่',
    'edit.location': 'ตำแหน่ง',
    'edit.candidateCriteria': 'เกณฑ์การคัดเลือกผู้สมัคร',
    'edit.companyId': 'ผู้ว่าจ้าง',
    'edit.company': 'ชื่อผู้ว่าจ้าง',
    'edit.jobTypeId': 'ประเภทงาน',
    'edit.jobManpowerId': 'แรงงาน',
    'edit.acceptingPosition': 'จำนวนตำแหน่งที่เปิดรับ',
    'edit.jobSalary': 'เงินเดือน',
    'edit.jobTime': 'เวลา',
    'edit.images': 'รูปภาพ',
    'edit.videos': 'วิดีโอ',
    'edit.jobOwnerLabel': 'เจ้าของงาน',
    'edit.noFileSelected': 'ยังไม่ได้เลือกไฟล์',
    'edit.imageOrVideoWillBeDisplayedHere': 'รูปภาพหรือวิดีโอจะแสดงที่นี่',
    'edit.enterWholeNumberOnly': 'ระบุเป็นตัวเลขจำนวนเต็มเท่านั้น',
    'edit.imagesAndVideos': 'รูปภาพและวิดีโอ',
    'edit.imageOrVideo': 'รูปภาพหรือวิดีโอ',
    'edit.jobType': 'ประเภทงาน',
    'edit.jobManpower': 'แรงงาน',
    'edit.orDragAndDropHere': 'หรือลากและวางไฟล์ที่นี่',
    'edit.pngJpgMax5MBGifMp4Max20MB': 'รองรับเฉพาะไฟล์รูปภาพ (JPG, PNG, GIF) ขนาดไฟล์ต้องไม่เกิน 5MB หรือวิดีโอ (MP4, WebM) ขนาดไฟล์ต้องไม่เกิน 20MB',
    'edit.uploadLimit': 'อัปโหลดได้สูงสุด {count} ไฟล์',
    'edit.uploadImageOrVideo': 'อัปโหลดรูปภาพหรือวิดีโอ',
    'edit.salaryAndWorkingTime': 'เงินเดือนและเวลาทำงาน',
    'edit.jobLocation': 'ตำแหน่งงาน',
    'edit.media': 'สื่อ',
    'edit.video': 'วิดีโอ',
    'edit.image': 'รูปภาพ',
    'edit.cancel': 'ยกเลิก',
    'edit.save': 'บันทึก',
    'edit.saving': 'กำลังบันทึก...',
    'edit.mediaSize':'ขนาดสื่อ',
    'edit.mediaDragDrop':'ลากและวางไฟล์ที่นี่, หรือคลิกเพื่อเลือกไฟล์',
    'edit.mediaUpload':'อัปโหลดรูปภาพหรือวิดีโอ',
    'edit.mediaLimit':'อัปโหลดได้สูงสุด {count} ไฟล์',
    'edit.mediaFormat':'รองรับเฉพาะไฟล์รูปภาพ (JPG, PNG, GIF)',
    'edit.mediaFileSize':'ขนาดไฟล์ต้องไม่เกิน {size}MB','edit.mediaRemove':'ลบสื่อ',
    'edit.uploadVideo':'อัปโหลดวิดีโอ',
    'edit.orDragAndDrop':'หรือลากและวางไฟล์ที่นี่',
    'edit.videoSize':'ขนาดวิดีโอ',
    'edit.confirmDelete':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'edit.confirmDeleteDescription':'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'edit.confirmDeleteYes':'ใช่, ลบ',
    'edit.confirmDeleteNo':'ไม่, ทำต่อ',
    'edit.confirmCancel':'คุณแน่ใจหรือไม่ว่าต้องการยกเลิก?',
    'edit.confirmCancelDescription':'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'edit.confirmCancelYes':'ใช่, ยกเลิก',
    'edit.confirmCancelNo':'ไม่, ทำต่อ',
    'edit.confirmDeleteTitleMedia':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'edit.confirmDeleteDescriptionMedia':'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'edit.confirmDeleteYesMedia':'ใช่, ลบ',
    'edit.confirmDeleteNoMedia':'ไม่, ทำต่อ',
    'edit.confirmDeleteTitleMediaDesc':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'edit.confirmDeleteDescriptionMediaDesc':'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'edit.confirmDeleteYesMediaDesc':'ใช่, ลบ',
    'edit.confirmDeleteNoMediaDesc':'ไม่, ทำต่อ',
    'edit.deleting':'กำลังลบ...',
    'edit.delete':'ลบ',
    'edit.deleteConfirmTitle':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'edit.deleteConfirmDescription':'',
    'edit.deleteConfirmYes':'ใช่, ลบ',
    'edit.deleteConfirmNo':'ไม่, ทำต่อ',
    'edit.deleteConfirmTitleMedia':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'edit.deleteConfirmDescriptionMedia':'',
    'edit.deleteConfirmYesMedia':'ใช่, ลบ',
    'edit.deleteConfirmNoMedia':'ไม่, ทำต่อ',
    'edit.deleteConfirmTitleMediaDesc':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'edit.deleteConfirmDescriptionMediaDesc':'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'edit.deleteConfirmYesMediaDesc':'ใช่, ลบ',
    'edit.deleteConfirmNoMediaDesc':'ไม่, ทำต่อ',
    'edit.uploading':'กำลังอัปโหลด...',
    'edit.upload':'อัปโหลด',
    'edit.previewHere':'Preview here',
    'edit.confirmDeleteDesc':'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'edit.confirmDeleteYesDesc':'ใช่, ลบ',
    'edit.confirmDeleteNoDesc':'ไม่, ทำต่อ',
    'edit.confirmDeleteTitleDesc':'คุณแน่ใจหรือไม่ว่าต้องการลบ?',
    'edit.confirmDeleteDescriptionDesc':'ข้อมูลที่คุณกรอกจะไม่ถูกบันทึก',
    'edit.selectJobType': 'เลือกประเภทงาน',
    'edit.selectJobManpower':'เลือกแรงงาน',
    'edit.titleMedia': 'รูปภาพ/วิดีโอหน้าปก',
    'edit.selectCompany':'เลือกผู้ว่าจ้าง',
    'edit.selectScore':'เลือกคะแนน',
    'edit.selectScoreType':'เลือกประเภทคะแนน',
    'edit.selectScoreValue':'เลือกคะแนน',
    'edit.selectScoreValuePlaceholder':'กรุณากรอกคะแนน',
    'edit.selectScoreValuePlaceholderDesc':'กรุณากรอกคะแนน',
    'edit.uploadingImage': 'กำลังอัปโหลด...',
    'edit.uploadingVideo': 'กำลังอัปโหลด...',
    'edit.uploadingTitleMedia': 'กำลังอัปโหลด...'
  },
  en: {
    // Job Details
    'jobDetail.apply': 'Apply Now',
    'jobDetail.requirements': 'Requirements',
    'jobDetail.benefits': 'Benefits',
    'jobDetail.description': 'Job Description',
    'jobDetail.location': 'Location',
    'jobDetail.type': 'Job Type',
    'jobDetail.experience': 'Experience',
    'jobDetail.education': 'Education',
    'jobDetail.expandedImage': 'Expanded Image',
    'jobDetail.selectedImage': 'Selected Image',
    'jobDetail.thumbnail': 'Thumbnail',
    'jobDetail.recommendedVideos': 'Recommended Videos',
    'jobDetail.licenseDocuments': 'License Documents',
    'jobDetail.certificateImage': 'Certificate Image',
    'jobDetail.defaultJobTitle': 'Farmer, Wheat Cultivation',
    'jobDetail.positionsAvailable': '{count} positions available',
    'jobDetail.interested': 'I\'m Interested',
    'jobDetail.alreadyInterested': 'Already Interested',
    'jobDetail.jobDetails': 'Job Details',
    'jobDetail.jobType': 'Job Type',
    'jobDetail.workDays': 'Working Days',
    'jobDetail.workHours': 'Working Hours',
    'jobDetail.qualifications': 'Qualifications',
    'jobDetail.workLocation': 'Work Location',
    'jobDetail.errors.cannotDelete': 'Cannot delete: the data has already been used',
    'jobDetail.errors.unknownError': 'An unknown error occurred. Please try again.',
    'jobDetail.errors.errorOccurred': 'Error',
    'jobDetail.errors.interestError': 'An error occurred while expressing interest in the job. Please try again.',
    'jobDetail.preview': 'Preview',
    'jobDetail.noVideosAvailable': 'No videos available at this time',
    'jobDetail.salaryStart': 'Salary Start',
    'jobDetail.workingHoursPerWeek': 'Working Time: {count} hours/month',
    'jobDetail.candidateCriteria': 'Candidate Criteria',

    'mapSection.workplaceMap': 'Workplace Map',
    'mapSection.workplaceLocation': 'Workplace Location',

    // Job Creation Form
    'create.pageTitle': 'Create New Job Posting',
    'create.backToList': 'Back to List',
    'create.basicInfo': 'Basic Information',
    'create.salaryAndTime': 'Salary and Working Hours',
    'create.jobDetails': 'Job Details',
    'create.workLocation': 'Work Location',
    'create.mediaSection': 'Images and Videos',

    'create.jobTitle': 'Job Title',
    'create.jobType': 'Job Type',
    'create.selectJobType': 'Select Job Type',
    'create.company': 'ManPower Demand',
    'create.selectCompany': 'Select ManPower Demand',
    'create.jobManpower': 'ManPower Supply',
    'create.selectJobManpower': 'Select ManPower Supply',
    'create.titleMedia': 'Cover Image/Video',
    'create.uploadImageOrVideo': 'Upload image or video',
    'create.dragAndDrop': 'or drag and drop here',
    'create.positions': 'Number of Positions',
    'create.numericOnly': 'Enter whole numbers only',
    'create.score': 'Score',
    'create.slide': 'Slide',
    'create.notSlide': 'Not Slide',
    'create.salaryStart': 'Starting Salary (THB)',
    'create.workingHoursPerWeek': 'Working Hours Per Month',
    'create.salaryEnd': 'Maximum Salary (THB)',
    'create.startDay': 'Start Day',
    'create.endDay': 'End Day',
    'create.startTime': 'Start Time',
    'create.endTime': 'End Time',
    'create.description': 'Job Description',
    'create.descPlaceholder': 'Explain job details, responsibilities',
    'create.qualifications': 'Qualifications',
    'create.qualiPlaceholder': 'Specify required qualifications such as age, gender, education',
    'create.criteria': 'Selection Criteria',
    'create.criteriaPlaceholder': 'Specify criteria for selecting applicants',
    'create.address': 'Address',
    'create.addressPlaceholder': 'Specify workplace address',
    'create.location': 'Coordinates (Latitude, Longitude)',
    'create.locationPlaceholder': '13.7563,100.5018',
    'create.locationHelp': 'Please specify coordinates in Latitude,Longitude format such as 13.7563,100.5018',
    'create.images': 'Images',
    'create.uploadImages': 'Upload Images',
    'create.imageTypes': 'PNG, JPG, GIF up to 10MB per file',
    'create.videos': 'Videos',
    'create.uploadVideos': 'Upload Videos',
    'create.videoTypes': 'MP4, WebM up to 100MB per file',

    // Days of week
    'create.monday': 'Monday',
    'create.tuesday': 'Tuesday',
    'create.wednesday': 'Wednesday',
    'create.thursday': 'Thursday',
    'create.friday': 'Friday',
    'create.saturday': 'Saturday',
    'create.sunday': 'Sunday',

    // Buttons
    'create.cancel': 'Cancel',
    'create.save': 'Save',
    'create.saving': 'Saving...',

    // Validation & errors
    'create.required': 'Required',
    'create.validationLocation': 'Please specify coordinates in Latitude,Longitude format such as 13.7563,100.5018',
    'create.fileFormatError': 'Please select only image or video files',
    'create.loading': 'Loading data...',
    'create.noCompany': 'No ManPower Demand data found',
    'create.noJobType': 'No job type data found',
    'create.noManpower': 'No ManPower Supply data found',

    // Modal texts
    'create.emptyManpowerTitle': 'No ManPower Supply Found',
    'create.emptyManpowerDesc': 'You need to create at least one ManPower Supply before creating a new job posting',
    'create.createManpower': 'Create ManPower Supply',
    'create.emptyCompanyTitle': 'No ManPower Demand Found',
    'create.emptyCompanyDesc': 'You need to create at least one ManPower Demand before creating a new job posting',
    'create.createCompany': 'Create ManPower Demand',
    'create.emptyJobTypeTitle': 'No Job Types Found',
    'create.emptyJobTypeDesc': 'You need to create at least one job type before creating a new job posting',
    'create.createJobType': 'Create Job Type',

    // Additional translations for create page
    'create.jobOwner': 'Job Owner',
    'create.jobOwnerPlaceholder': 'Enter job owner name',
    'create.fileNotSelected': 'No file selected',
    'create.preview': 'Image or video will appear here',
    'create.removeMedia': 'Remove media',
    'create.removeImage': 'Remove image',
    'create.removeVideo': 'Remove video',
    'create.workingDays': 'Working Days',
    'create.workingHours': 'Working Hours',
    'create.to': 'to',
    'create.jobDescription': 'Job Description',
    'create.jobDescriptionPlaceholder': 'Explain job details, responsibilities',
    'create.successTitle': 'Job Created Successfully',
    'create.successDescription': 'The job has been created successfully',
    'create.viewJob': 'View Job',
    'create.errorTitle': 'Error Occurred',
    'create.errorDescription': 'Could not create job posting. Please try again.',
    'create.goBack': 'Go Back',
    'create.selectMedia': 'Select image or video',
    'create.uploadLimit': 'Upload up to {count} files',
    'create.salaryRange': 'Salary Range',
    'create.acceptingPositions': 'Number of Positions Available',
    'create.scoreType': 'Score Type',
    'create.scoreValue': 'Score Value',
    'create.dragDropHint': 'Drag and drop files here, or click to select files',
    'create.workingPeriod': 'Working Period',
    'create.dayFrom': 'From day',
    'create.dayTo': 'To day',
    'create.timeFrom': 'From time',
    'create.timeTo': 'To time',
    'create.additionalDetails': 'Additional Details',
    'create.locationDetails': 'Location Details',
    'create.mediaUpload': 'Media Upload',
    'create.languageSelector': 'Select Language',
    'create.thai': 'Thai',
    'create.english': 'English',
    'create.validationRequired': 'This field is required',
    'create.validationNumber': 'Please enter numbers only',
    'create.validationPositiveNumber': 'Please enter a number greater than 0',
    'create.validationMaxLength': 'Maximum {count} characters allowed',
    'create.validationImage': 'Only image files are supported (JPG, PNG, GIF)',
    'create.validationVideo': 'Only video files are supported (MP4, WebM)',
    'create.validationFileSize': 'File size must not exceed {size}MB',
    'create.confirmCancel': 'Are you sure you want to cancel?',
    'create.confirmCancelDescription': 'Your entered data will not be saved',
    'create.confirmCancelYes': 'Yes, cancel',
    'create.confirmCancelNo': 'No, continue',
    'create.chooseLocation': 'Choose location on map',
    'create.browse': 'Browse files',
    'create.jobOwnerLabel': 'Job Owner',
    'create.noFileSelected': 'No file selected',
    'create.imageOrVideoWillBeDisplayedHere': 'Image or video will be displayed here',
    'create.enterWholeNumberOnly': 'Enter whole numbers only',
    'create.imagesAndVideos': 'Images and Videos',
    'create.candidateCriteria': 'Selection Criteria',
    'create.startDate': 'Start Day',
    'create.endDate': 'End Day',
    'create.imageOrVideo': 'Image or Video',
    'create.fileSizeError': 'File size must not exceed 500KB',
    'create.close': 'Close',
    'create.emptyJobTypesTitle': 'No Job Types Found',
    'create.emptyJobTypesDesc': 'You need to create at least one job type before creating a new job posting',
    'create.emptyJobTypesCreate': 'Create Job Type',
    'create.errorInvalidFile': 'Please select only image or video files',
    'create.acceptFormat': 'Accept format',

    'edit.backToJobs': 'Back to Jobs',
    'edit.editJob': 'Edit Job',
    'edit.loading': 'Loading',
    'edit.error': 'Error',
    'edit.success': 'Job edited successfully',
    'edit.goBack': 'Go Back',
    'edit.jobDetails': 'Job Details',
    'edit.jobTitle': 'Job Title',
    'edit.jobOwner': 'Job Owner',
    'edit.score': 'Score',
    'edit.salaryStart': 'Salary Start',
    'edit.salaryEnd': 'Salary End',
    'edit.startDate': 'Start Date',
    'edit.endDate': 'End Date',
    'edit.jobDate': 'Job Date',
    'edit.timeStart': 'Time Start',
    'edit.timeEnd': 'Time End',
    'edit.description': 'Description',
    'edit.qualifications': 'Qualifications',
    'edit.address': 'Address',
    'edit.location': 'Location',
    'edit.candidateCriteria': 'Candidate Criteria',
    'edit.companyId': 'ManPower Demand',
    'edit.company': 'ManPower Demand',
    'edit.jobTypeId': 'Job Type',
    'edit.jobManpowerId': 'ManPower Supply',
    'edit.acceptingPosition': 'Accepting Position',
    'edit.jobSalary': 'Job Salary',
    'edit.jobTime': 'Job Time',
    'edit.images': 'Images',
    'edit.videos': 'Videos',
    'edit.jobOwnerLabel': 'Job Owner',
    'edit.noFileSelected': 'No file selected',
    'edit.imageOrVideoWillBeDisplayedHere': 'Image or video will be displayed here',
    'edit.enterWholeNumberOnly': 'Enter whole numbers only',
    'edit.imagesAndVideos': 'Images and Videos',
    'edit.imageOrVideo': 'Image or Video',
    'edit.jobType': 'Job Type',
    'edit.jobManpower': 'ManPower Supply',
    'edit.uploadLimit': 'Upload limit',
    'edit.pngJpgMax5MBGifMp4Max20MB': 'PNG, JPG, GIF, MP4, WebM',
    'edit.orDragAndDropHere': 'Or drag and drop here',
    'edit.uploadImageOrVideo': 'Upload image or video',
    'edit.salaryAndWorkingTime': 'Salary and Working Time',
    'edit.jobLocation': 'Job Location',
    'edit.media': 'Media',
    'edit.video': 'Video',
    'edit.image': 'Image',
    'edit.cancel': 'Cancel',
    'edit.save': 'Save',
    'edit.saving': 'Saving...',
    'edit.mediaSize': 'Media size',
    'edit.mediaDragDrop': 'Drag and drop files here, or click to select files',
    'edit.mediaUpload': 'Upload image or video',
    'edit.mediaLimit': 'Upload up to {count} files',
    'edit.mediaFormat': 'Only image files are supported (JPG, PNG, GIF)',
    'edit.mediaFileSize': 'File size must not exceed {size}MB','edit.mediaRemove': 'Remove media',
    'edit.videoSize':'Video size must not exceed {size}MB',
    'edit.imageSize':'Image size must not exceed {size}MB',
    'edit.uploadVideo':'Upload video',
    'edit.orDragAndDrop':'Or drag and drop here',
    'edit.uploadImage':'Upload image',
    'edit.confirmDelete':'Are you sure you want to delete?',
    'edit.confirmDeleteDescription':'',
    'edit.confirmDeleteYes':'Yes, delete',
    'edit.confirmDeleteNo':'No, continue',
    'edit.confirmCancel':'Are you sure you want to cancel?',
    'edit.confirmCancelDescription':'',
    'edit.confirmCancelYes':'Yes, cancel',
    'edit.confirmCancelNo':'No, continue',
    'edit.confirmDeleteTitleMedia':'Are you sure you want to delete?',
    'edit.confirmDeleteDescriptionMedia':'',
    'edit.confirmDeleteYesMedia':'Yes, delete',
    'edit.confirmDeleteNoMedia':'No, continue',
    'edit.confirmDeleteTitleMediaDesc':'Are you sure you want to delete?',
    'edit.confirmDeleteDescriptionMediaDesc':'',
    'edit.confirmDeleteYesMediaDesc':'Yes, delete',
    'edit.confirmDeleteNoMediaDesc':'No, continue',
    'edit.deleting':'Deleting...',
    'edit.delete':'Delete',
    'edit.deleteConfirm':'Are you sure you want to delete?',
    'edit.deleteConfirmDescription':'',
    'edit.deleteConfirmYes':'Yes, delete',
    'edit.deleteConfirmNo':'No, continue',
    'edit.deleteConfirmTitle':'Are you sure you want to delete?',
    'edit.deleteConfirmTitleMedia':'Are you sure you want to delete?',
    'edit.deleteConfirmDescriptionMedia':'',
    'edit.deleteConfirmYesMedia':'Yes, delete',
    'edit.deleteConfirmNoMedia':'No, continue',
    'edit.deleteConfirmTitleMediaDesc':'Are you sure you want to delete?',
    'edit.deleteConfirmDescriptionMediaDesc':'',
    'edit.deleteConfirmYesMediaDesc':'Yes, delete',
    'edit.deleteConfirmNoMediaDesc':'No, continue',
    'edit.uploading':'Uploading...',
    'edit.upload':'Upload',
    'edit.previewHere':'Preview here',
    'edit.confirmDeleteDesc':'Are you sure you want to delete?',
    'edit.confirmDeleteYesDesc':'Yes, delete',
    'edit.confirmDeleteNoDesc':'No, continue',
    'edit.confirmDeleteTitleDesc':'Are you sure you want to delete?',
    'edit.confirmDeleteDescriptionDesc':'',
    'edit.selectJobType':'Select Job Type',
    'edit.selectJobManpower':'Select Job Manpower',
    'edit.titleMedia':'Title Media',
    'edit.selectCompany':'Select Company',
    'edit.selectScore':'Select Score',
    'edit.selectScoreType':'Select Score Type',
    'edit.selectScoreValue':'Select Score Value',
    'edit.selectScoreValuePlaceholder':'Enter score value',
    'edit.selectScoreValuePlaceholderDesc':'Enter score value',
    'edit.uploadingImage': 'Uploading...',
    'edit.uploadingVideo': 'Uploading...',
    'edit.uploadingTitleMedia': 'Uploading...'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Initialize with Thai language by default
  const [language1, setLanguageState] = useState<Language1>('th');
  const [isClient, setIsClient] = useState(false);

  // Only run on client side
  useEffect(() => {
    setIsClient(true);
    const saved = localStorage.getItem('jobyamLanguage');
    if (saved && (saved === 'th' || saved === 'en')) {
      setLanguageState(saved as Language1);
    }
  }, []);

  useEffect(() => {
    if (isClient) {
      localStorage.setItem('jobyamLanguage', language1);
      document.documentElement.lang = language1;
    }
  }, [language1, isClient]);

  const setLanguage1 = (lang: Language1) => {
    setLanguageState(lang);
  };

  // เพิ่มฟังก์ชัน t ที่สมบูรณ์
  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language1][key] || key;

    // ถ้ามีพารามิเตอร์ให้แทนที่ตามค่าที่ส่งมา
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        const regex = new RegExp(`{${param}}`, 'g');
        text = text.replace(regex, String(value));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language1, setLanguage1, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage1() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage1 must be used within a LanguageProvider');
  }
  return context;
}
